examples/apache_metrics.mtail
=> Fix another typo in examples/apache_metrics.mtail.

Makefile
I should be covered by a corp CLA of which I am a member. We'll see what the bot says 😄.
=> Install goyacc in `install_gen_deps` target (fixes #51).

examples/apache_combined.mtail
Add support for the western hemisphere in the example
=> apache_combined.mtail only matches positive timezones

.gitlab-ci.yml
Add a GitLab CI configuration for building artifacts on GitLab.
=> Add GitLab-CI yaml

tailer/tail.go
=> also initialize partials for named pipes

examples/rails.mtail
Parses the total number of started requests by verb, and then completed
requests by status code. It also adds a request latency histogram using
buckets
=> Add example file for parsing rails production log

docs/Interoperability.md
=> Propose fix some typos

.circleci/config.yml
This uses the Circle TAG for the release tag.
=> Fixed deploy tag

mtail/mtail.go, mtail/mtail_test.go, tailer/tail.go, tailer/tail_test.go, testutil/reader.go, vm/compiler.go, vm/lexer_test.go, vm/position.go, vm/types.go, vm/types_test.go, vm/walk.go, watcher/fake_watcher.go, watcher/log_watcher_test.go
Hi @jaqx0r ,
I fixed some trivial issues reported by *megacheck*, *maligned*, *golint*, and *vetshadow*. I signed the CLA already. 
Thanks!
I will be double-checking the CI-tests tomorrow, and fix them.
=> Fix linter issues

docs/Programming-Guide.md, examples/apache_metrics.mtail, vm/parser_test.go
* Initialize all buckets with an increment by 0.
* Update Programming Guide to match the example.
=> Improve apache metrics histogram example

docs/Programming-Guide.md
=> Fixed a typo

cmd/mtail/main.go, internal/metrics/store.go, internal/mtail/mtail.go, internal/mtail/options.go
adding option to configure StoreExpireTickInterval
Fixed bug where `Store.Expire()` was only invoked once
=> adding option to configure StoreExpireTickInterval and Fixed bug where `Store.Expire()` was only invoked once

examples/histogram.mtail
Looking at the histogram documentation and examples, I felt a bit lost at first. In hindsight, it all seems so simple. Wanted to add some depth to the example so nobody else stumbles on the silly stuff like me.
=> histogram example improvement

examples/postfix.mtail
* Added forward slash matching in application pattern
* Made a regex of smtpd matching to allow for "submission/smtpd"
=> [examples] Fixed postfix matching with submission

.github/workflows/cirrus-ci.yml
In order to depend on this we need an action I believe, so here's one from https://github.com/cirrus-actions/check-suite
=> Add an action that checks when the Cirrus CI was successful.

.github/workflows/auto-review.yml, .github/workflows/automerge.yml
Based on https://github.com/pascalgn/automerge-action#configuration but for now
restrict to just dependabot and jaqx0r actors.
=> Add an auto-merge action.

.github/workflows/auto-review.yml, .github/workflows/automerge.yml
Put the if statment in the job rather than the step.  Let it fire on specific
types of pull request.
=> Repair the auto-review action.

.github/workflows/automerge.yml
See https://github.com/pascalgn/automerge-action/issues/46 for gory details.
Hope springs from github/roadmap#107
=> Don't automerge jaqx0r's changes as actions don't work on forks.

internal/mtail/unix_socket_export_integration_test.go
Untag this test as integration so that it runs with the rest of the tests.
Then, learn why it's got a compile error in it.. then learn why it
fails... Attempt to fix the use of a root-only filename but fail, and so in the
meantime mark it for skip.
=> Make new test compile, but not work.

cmd/mtail/main.go, internal/exporter/export.go, internal/exporter/prometheus_test.go, internal/mtail/mtail.go, internal/mtail/options.go, internal/mtail/testing.go, internal/mtail/unix_socket_export_integration_test.go, internal/tailer/tail.go, internal/tailer/tail_test.go, internal/vm/loader.go, internal/vm/vm_integration_test.go
Homogenise the style for Options passed to each of the main modules in `mtail`.  The `mtail` options remain the apply-pattern style which I'm still not sure about, however.
=> Convert all functional options to a typed Option.

.github/workflows/ci.yml
Speed up dependency downloads.
=> Set GOPROXY environment variable.

.github/workflows/benchmark.yml
Reduce count of benchmarks to 5.
Put the issue body in markdown quotes.
=> Fix encoding of readFileSync.

.github/workflows/benchmark.yml
Remove stray \n from the comment.
=> Strip the HTML of just the table.

.github/workflows/benchmark-done.yml, .github/workflows/ci-done.yml
Use id to name steps for reference later, and fix how set-output is called.
=> Fix more errors in config.

internal/tailer/tail.go
=> Move a debug log message to level 2 verbosity.

Makefile
Dependabot creates a branch with a slash in the name, but then it is not read
by the Makefile rule at the top of the file because it already exists in the
environment, so the `tr` substitution didn't kick in.
=> Substitute slashes for hyphens in BASE_REF and HEAD_REF consistently.

.github/workflows/automerge.yml
I don't know how graphql works, so just use this action for now.
=> Use alexwilson/enable-github-automerge-action to automerge.

internal/tailer/logstream/pipestream_test.go
Use O_WRONLY to open the fifo in test means we ensure we have a
non-EOF-signalling pipe for the pipestream when it gets to fd.Read().  This is
possible if the scheduler schedules the new goroutine before the test proceeds.
Not convinced that there isn't still a race in production.
=> Avoid a race by opening the write end first.

internal/tailer/logstream/filestream.go
=> Reopen the file stream if the read error is ESTALE.

internal/tailer/logstream/pipestream_test.go
We're expecting the log lines to get written, but if we cancel right away we
don't wait for the read to occur.  Wait for the pipestream to engage the waker
so we know we have passed a read.
=> Synchronise the pipestream test to avoid a race on cancel.

Makefile, TODO, internal/mtail/examples_integration_test.go, internal/mtail/read_pipe_integration_test.go, internal/tailer/logstream/dgramstream.go, internal/tailer/logstream/dgramstream_test.go, internal/tailer/logstream/filestream.go, internal/tailer/logstream/filestream_test.go, internal/tailer/logstream/logstream.go, internal/tailer/logstream/pipestream.go, internal/tailer/logstream/pipestream_test.go, internal/tailer/logstream/socketstream.go, internal/tailer/logstream/socketstream_test.go, internal/tailer/tail.go, internal/testutil/norace.go, internal/testutil/race.go, internal/testutil/timeout.go
This is a partial implementation of #276 but it is not yet exposed to the user.
=> Stream from Unix stream and datagram sockets.

internal/runtime/httpstatus.go
=> Test that we have a handle before trying to read into it.

internal/mtail/prog_load_integration_test.go, internal/runtime/httpstatus.go, internal/runtime/runtime.go
=> If a program no longer exists then unload it when SIGHUP'd.

Makefile, docs/Interoperability.md, internal/testutil/race.go
=> Update interoperability documentation.

docs/Deploying.md, docs/faq.md
Add docs for how to set up automatic reloads and explain why mtail doesn't do
it.
Fixes: #560
=> mtail doesn't automatically reload programmes.

.github/workflows/ci-done.yml
["I hate YAML"](https://twitter.com/voltagex/status/1424287442757054464) -- @voltagex
=> Fix a typo.

cmd/mtail/main.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Make one-shot Prometheus emit prog label and metric timestamp flags

.github/workflows/auto-review.yml, .github/workflows/benchmark-done.yml, .github/workflows/ci-done.yml
Documented https://github.com/actions/github-script but only discovered in CI failure :'(
=> Update github script code to the v5 API after the breaking change.

TODO, internal/runtime/compiler/ast/ast.go, internal/runtime/compiler/checker/checker.go, internal/runtime/compiler/codegen/codegen.go, internal/runtime/compiler/codegen/codegen_test.go, internal/runtime/compiler/types/types.go, internal/runtime/compiler/types/types_test.go, internal/runtime/fuzz.go, internal/runtime/options.go, internal/runtime/runtime.go, internal/runtime/runtime_integration_test.go, internal/runtime/vm/vm.go, internal/runtime/vm/vm_test.go
Improve strictness of logical operator typechecking.
Clean up code where that caused breakages, improve test coverage.
=> Logical op types

examples/postfix.mtail
Since 2017 I changed my name and I would like to remove all references to the old one.
=> Update my name and email address

internal/tailer/tail.go, internal/tailer/tail_test.go
The Tailer.PollLogPatterns and Tailer.Ignore methods currently abort they
encounter files that cause errors on os.Stat or os.Getwd, which can be caused
by race conditions (file removed after filepath.Glob was called) or broken
symlinks. This can make mtail crash on start-up, but also prevents good log
files from being processed due to the early return of PollLogPatterns.
This commit changes PollLogPatterns to log the errors and continue the
operation. In Ignore the errors now are handled by returning `true`, so the
file is ignored.
Closes: #609
=> Skip logfiles that cannot be read

cmd/mtail/main.go, internal/exporter/export.go, internal/exporter/export_test.go, internal/mtail/exec_integration_test.go, internal/runtime/runtime.go, internal/runtime/runtime_test.go, internal/tailer/logstream/logstream.go, internal/tailer/logstream/logstream_test.go, internal/tailer/tail.go, internal/tailer/tail_test.go
=> Do not pass a nil `WaitGroup` to the exporter in one_shot mode.

docs/Deploying.md, internal/mtail/examples_integration_unix_test.go, internal/mtail/exec_integration_test.go, internal/mtail/log_deletion_integration_unix_test.go, internal/mtail/log_rotation_integration_unix_test.go, internal/mtail/permission_denied_integration_unix_test.go, internal/mtail/read_pipe_integration_unix_test.go, internal/runtime/fuzz.go, internal/tailer/logstream/cancel.go, internal/tailer/logstream/dgramstream_unix_test.go, internal/tailer/logstream/filestream.go, internal/tailer/logstream/filestream_test.go, internal/tailer/logstream/filestream_unix_test.go, internal/tailer/logstream/logstream.go, internal/tailer/logstream/logstream_test.go, internal/tailer/logstream/logstream_unix_test.go, internal/tailer/logstream/pipestream.go, internal/tailer/logstream/pipestream_unix_test.go, internal/tailer/logstream/socketstream.go, internal/tailer/logstream/socketstream_unix_test.go, internal/tailer/tail.go, internal/tailer/tail_test.go, internal/tailer/tail_unix_test.go, internal/tailer/tail_windows_test.go, internal/testutil/norace.go, internal/testutil/race.go, internal/testutil/stdin.go
=> feat: Read `stdin` when the log name is `-`.

.github/workflows/release.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-goreleaser
and
https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator
Fixes: #836
=> ci: Sign release artifacts.

.github/workflows/release.yml
=> ci: Verify SLSA3 provenance after release.

.github/workflows/release.yml
=> ci: Try to fix release signature verification.

.github/workflows/remove-old-package-versions.yml
Keep a minimum of 10 versions.
=> ci: Add a workflow to delete old packages.
