google/mtail

- testdata/rsyncd.json
- vm/parser.y
- vm/vm.go
I don't know why this was done originally, but sorting the keys breaks most multi-dimensional metrics. The test cases seem to have been very lucky.
> Stop sorting keys.

- exporter/export_prometheus.go
- exporter/export_prometheus_test.go
Returning the "last updated" time for a counter is not correct for
Prometheus metrics.  It's recommended to omit the timestamp and allow
the server to pick the timestamp.
> Remove timestamps from Prometheus exporter

- examples/apache_combined.mtail
Add a parser for the commonly used apache "combined"[0] log format.
[0]: http://httpd.apache.org/docs/2.2/mod/mod_log_config.html
> Add example for apache combined logs

- examples/apache_metrics.mtail
Add a new custom apache LogFormat for getting the most out of apache
request logging.
`LogFormat "%v:%p %R %m %>s %H conn=%X %D %O %I %k" metrics`
New metrics are now possible:
* apache_http_requests_total
* apache_http_connections_total (only partly useful)
* apache_http_requests_time_microseconds_total
* apache_http_sent_bytes_total
* apache_http_recieved_bytes_total
All of these metrics are by server_port, handler, request_method,
request_status, request_protocol.
> Add example apache metrics-friendly config

- exporter/export.go
I noticed that once statsd or graphite exporters were enabled, CPU utilization would go crazy after a short while. I played around with pprof and noticed high GC calls. The root cause was the go routine to proactively read and discard incoming socket data performing *large* numbers of non-blocking socket reads. This should be unnecessary to keep the writer unblocked.
> remove socket read goroutine; creating garbage, triggering GC and high CPU

- exporter/collectd.go
- exporter/export_test.go
- exporter/prometheus.go
- exporter/prometheus_test.go
Related to Issue #15 
The `timer` metric is specific to the StatsD exporter. For the other exporters, it should be exposed as a `gauge`.
Prometheus and CollectD exporters publish their metrics with the type/kind info. In these cases, we ensure that `timer` is published as `gauge`.
Graphite and Varz don't expect metric type/kind info so I've not made any changes there.
> Timer as gauge for Prometheus/CollectD

- vm/vm.go
This makes it possible to follow the 'str' instructions.
> Output string constants when dumping bytecode.

- mtail/mtail.go
- Lines read in one_shot mode are sent to the VM with trailing newlines
still intact, which means simple regexes like /^1$/ will never match
in one_shot mode.
- When EOF is reached, the current line buffer is sent, even if it's
empty.
The former is fixed by trimming trailing newlines from the line before
sending it to the VM. The latter is fixed by not sending an empty string
on EOF.
Empty lines are still passed through as before.
> Fix two bugs in one_shot line handling.

- tailer/tail.go
fsnotify has the inherent problem that the Watcher.Remove method
relies on events still being read from the events channel
(https://github.com/fsnotify/fsnotify/blob/master/inotify.go#L158). However,
the mtail code stops reading from the event channel until
Watcher.Remove has returned. Certain events, happening with the right
timing, can trigger this deadlock. This leads to
https://github.com/google/mtail/issues/27 , i.e. now and then, on
systems where logfiles are rotated away, mtail hangs.
This PR fixes the problem by running the Watcher.Remove call in its
own goroutine. I'm not entirely sure about undesired side effects, but
in our large-scale mtail setup at SoundCloud, it fixed the original
problem and didn't cause any new ones so far.
Ideally, we should have a test for the bug, but …
> Fix deadlock on removal of watches

- tailer/tail.go
This pull request converts the type of an inode in the stat object to the type required by the function. This enables mtail to compile on platforms other than linux and darwin.
> convert type for other platforms

- mtail/mtail.go
Due having a placeholder in the string by bet that this is a typo.
> Replace glog.Error with glog.Errorf

- vm/loader.go
I just run mtail, test a simple program, and found that when program has syntax error, mtail will not print any error messages. 
So I hack the code and fix this problem.
> Return error when program loading failed

- exporter/prometheus.go
- exporter/prometheus_test.go
This fixes a problem with metrics export when a label value includes double quotes (I'm evil and have a cron job text in a label value when exporting stuff from cron.log)
> Use string quoting for prometheus export

- exporter/export.go
When pushing metrics e.g. to graphite the default verbosity spams logs a
little I'd say, e.g.:
I1107 19:58:30.027436   14445 export.go:119] pushing to XXX
I1107 19:58:30.028448   14445 export.go:104] Sent 53 bytes
I1107 19:58:30.028472   14445 export.go:104] Sent 57 bytes
I1107 19:58:30.028499   14445 export.go:104] Sent 83 bytes
I1107 19:58:30.028513   14445 export.go:104] Sent 82 bytes
I1107 19:58:30.028539   14445 export.go:104] Sent 81 bytes
I1107 19:58:30.028578   14445 export.go:104] Sent 65 bytes
I1107 19:58:30.028595   14445 export.go:104] Sent 64 bytes
I1107 19:58:30.028610   14445 export.go:104] Sent 71 bytes
> exporter: increase logging verbosity for metric pushes

- exporter/collectd.go
- exporter/graphite.go
- exporter/statsd.go
Useful for example to further namespace metrics by host or other criteria.
> exporter: add prefix option for graphite/statsd metrics

- examples/apache_metrics.mtail
* Switch from microseconds to seconds
* Add 15s bucket
* Add _bucket suffix to buckets
* Use label "code", not "status", and drop "request_" prefix
* Move aborted/closed to label name
/cc @SuperQ
> Follow standard prometheus naming for HTTP metrics

- vm/checker_test.go
- vm/codegen_test.go
- vm/lexer_test.go
Set `deep.CompareUnexportedFields` to `true` if `deep.Equal`
is used to compare structs with unexported fields.
> compare unexported fields with deep.Equal

- vm/loader.go
- vm/loader_test.go
Ignore "hidden" program files that start with a `.`.  This avoids
attempting to load temp files deployed by config management systems.
> Ignore hidden program files

- exporter/prometheus.go
- exporter/prometheus_test.go
- metrics/metric_test.go
Prometheus creates instance labels at discovery time.  It is against
best practices to include it in metric output.
> Remove instance label from Prometheus format

- main.go
- mtail/mtail.go
* Add a bit of logic between parsing flags and instantiating mtail
instance to decide whether to use an implicit global bind
* Updated `MtailServer` to not munge `port` since the value in `o` is
already corrected.
> Resolves #82 allow specific bind interface

- examples/rails.mtail
An error 500 will print "Internal Server Error" as the description of
the status code, this does not matches `\w+` as the parsing will stop in
the first space character making the whole line to be excluded.
This commit fixes this by using the dot char to match instead.
> Fix rails sample in regards to parsing errors 500

- docs/index.md
As far as I see, `docs/...` are not used to build something and references to `.md` files are okay (and that's what github expects to make links clickable instead of 404).
> Make links at `index.md` clickable

- metrics/store_test.go
Tests the ability to:
- add two metrics with the same name and different type (int, float)
- this is done for both the same program and different program.
> Fix #130: test adding metrics of different types to a store.

- docs/Building.md
- docs/Deploying.md
- docs/Interoperability.md
- docs/Language.md
- docs/Testing.md
Otherwise `go get` from go1.9.2 failed with
```
$ go get https://github.com/google/mtail
package https:/github.com/google/mtail: "https://" not allowed in import path
```
> Fix tl;dr building recipe and some links

- .circleci/config.yml
- .gitignore
- .travis.yml
- Makefile
1. Adds crossbuilds for amd64 on Linux/Darwin/Windows using gox
2. Adds deploy step to both Travis and Circle since I couldn't work out which is current. The deploy step only triggers on commits with tags.
3. You'll need to specify GH api keys for both to make this work.
> Adding cross-building to Makefile & Travis

- mtail/mtail.go
- vm/checker.go
- vm/lexer.go
- vm/loader.go
- watcher/log_watcher_test.go
Hi @jaqx0r ,
I fixed some [codespell](https://github.com/lucasdemarchi/codespell) issues. This tool could be integrated to the CI.
```
$ codespell -S vendor*,*git/objects*
WARNING: Binary file: ./logo.png 
WARNING: Binary file: ./.git/index 
./tailer/tail_test.go:110: nd  ==> and, 2nd
./tailer/tail.go:210: Seeked  ==> Sought
./tailer/tail.go:232: seeked  ==> sought
```
> fix some codespell issues

- docs/Programming-Guide.md
03 format is for Kitchen
```
package main
import (
"time"
"fmt"
)
func main(){
fmt.Println(time.Parse("2006/01/02 03", "2018/04/09 00"))
// 2018-04-09 00:00:00 +0000 UTC <nil>
fmt.Println(time.Parse("2006/01/02 03", "2018/04/09 12"))
// 2018-04-09 12:00:00 +0000 UTC <nil>
fmt.Println(time.Parse("2006/01/02 03", "2018/04/09 13"))
// 0001-01-01 00:00:00 +0000 UTC parsing time "2018/04/09 13": hour out of range
}
```
> [docs] change time.Parse example default format

- Makefile
When building (`make`-ing) on a machine with a non-GNU find (Mac OSX, Alpine, etc), the `-printf` command is not available.
Since the purpose is to find FOLDERS where Go files exist, `printf` has been replaced with `exec`, which is supported on all `find` versions.
```diff
-PACKAGES := $(shell find . -name '*.go' -printf '%h\n' | sort -u)
+PACKAGES := $(shell find . -name '*.go' -exec dirname {} \; | sort -u)
```
```
Cloning into '/go/src/github.com/google/mtail'...
find: unrecognized: -printf
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.
Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'
-L,-follow	Follow symlinks
-H …
```
> Non-GNU Find does not support `-printf`

- Dockerfile
- README.md
- docs/Building.md
- hooks/build
- hooks/post_checkout
* Automated Builds on Docker Hub!
* 96% Smaller Builds!
* Super Sexy Container Labelling!  (I heard that Google LOVES metadata!)
```
$ docker images mtail
REPOSITORY      TAG                IMAGE ID            CREATED             SIZE
mtail           before             a02800fe77ff        4 hours ago         369MB
mtail           docker-builder     3a0c3263d397        3 minutes ago       14.9MB
$ docker inspect mtail:docker-builder | jq .[0].Config.Labels
{
"org.label-schema.build-date": "2018-04-17T17:22:47Z",
"org.label-schema.description": "extract whitebox monitoring data from application logs for collection in a timeseries database",
"org.label-schema.name": "mtail",
"org.label-schema.schema-version": "1.0",
"org.label-schema.url": "https://github.com/google/mtail", …
```
> Docker Automated Builds

- metrics/store.go
- metrics/store_test.go
When a new metric is added via store.Add:
- checks if there's another metric with the same labels
- if so, copies LabelValues in the new metric
- pop the old one from the array
> WIP: #127 merge duplicate metrics instead of adding them.

- docs/Programming-Guide.md
The example walks through an example where the request time SLI is 0.555555555 (nine fives), but the last sentence confuses the SLI and wording reverts to five nines.
> Minor typo in example "five nines" vs "nine fives"

- .gitlab-ci.yml
Fix: gitlab-ci stage test failing because of missing step ( installing dependencies ).
> Fix: gitlab-ci stage test failing

- metrics/store.go
- mtail/mtail_test.go
The PR addresses two problems with duplicated metrics:
- counters w/o labels weren't correctly handled, as even an empty new counter already contains a single value (zero);
- metrics with labels weren't handled by dedup at all.
> Correctly handle duplicated metrics

- tests/new_prog_test.sh
- vm/mcp.go
watcher.Update event might not be received when a new file is added into
progs directory. For example, when RPM is installing a package, it
doesn't change mtime on the files, thus watcher.Update event is never
received on the actual program file and the programs installed by RPM
are never loaded.
I0627 12:11:59.401242  840953 log_watcher.go:89] watcher event "/etc/mtail/messages.mtail;5b3354df": RENAME
I0627 12:11:59.401267  840953 log_watcher.go:89] watcher event "/etc/mtail/messages.mtail": CREATE
Fix this by loading programs right after watcher.Create event.
> vm: load programs right after watcher.Create event

- tailer/tail.go
Hello.
mtail didn't parse after logrotate command.
"event CREATE" happend before "event REMOVE".
memo: logrotate executed at 00:00 o'clock
```
> grep 'log_watcher.go:89' mtail.INFO | grep -v WRITE
I0808 00:00:01.955989   24622 log_watcher.go:89] watcher event "/var/log/a.log": RENAME
I0808 00:00:01.956446   24622 log_watcher.go:89] watcher event "/var/log/a.log": RENAME
I0808 00:00:01.956626   24622 log_watcher.go:89] watcher event "/var/log/a.log": CREATE
I0808 00:00:02.705517   24622 log_watcher.go:89] watcher event "/var/log/a.log": CHMOD
I0808 00:36:02.327719   24622 log_watcher.go:89] watcher event "/var/log/a.log": CHMOD
I0808 00:36:02.327882   24622 log_watcher.go:89] watcher event "/var/log/a.log": REMOVE
```
```
grep REMOVE mtail.INFO -A 30
I0808 00:36:02.327738   24622 …
```
> "event CREATE" happend before "event REMOVE" when used logrotate command.

- vm/vm.go
Process memory grows because timeMemos in VM holds all reference to unique time spec strings in the log. Using LRU cache saves memory consumption.
> vm timeMemos on LRU cache

- docs/Language.md
> Fixing a typo in documentation

- Makefile
- cmd/mtail/main.go
- internal/mtail/mtail.go
- internal/mtail/mtail_test.go
- internal/mtail/options.go
* Refactor build info from a string into a struct.
* Add git branch to build info.
* Add a Prometheus build info version metric.
> Add Prometheus build info metric.

- Dockerfile
Commit #3bfdc27 broke the Dockerfile. I.e. `COPY --from=builder /go/bin/mtail /usr/bin/mtail` is trying to copy from a non-existent file.
> Add PREFIX to make install

- emgen/emgen.go
- exporter/prometheus.go
- metrics/datum/buckets.go
- metrics/datum/datum.go
- metrics/metric.go
- testdata/reader.go
- vm/ast.go
- vm/codegen.go
- vm/lexer.go
- vm/lexer_test.go
- vm/parser.y
- vm/types.go
It still needs some work, testing, and docs, but I'd like your feedback. I'm completely sure about the new datum `Buckets` and the syntax.
A histogram is defined as `histogram <name> with 0, .1, .3, 1.`. It has the same syntax as the other metrics plus the keyword `with` to define the metric's buckets.
A histogram always uses the datum `Buckets`, when a new value
is assigned to the metric (`iset`), it will:
+ increment the counter for the observed value.
+ increment the total count.
+ update the total sum of all the observations.
Thank you.
> [WIP] add support for histogram

- examples/apache_metrics.mtail
Please check the conversion. Ideally it should be ,
$time_us / 1000000 or $time_us * 0.000001
> Microsecond to second conversion was wrong.

- examples/rails.mtail
- internal/vm/vm.go
Prometheus best practice[0] is to use base units. Use seconds
instead of milliseconds.
[0]: https://prometheus.io/docs/practices/naming/#base-units
> Use base units for metrics

- cmd/mtail/main.go
- internal/mtail/mtail.go
- internal/mtail/mtail_test.go
- internal/mtail/options.go
- internal/tailer/tail.go
This PR is related to this issue https://github.com/google/mtail/issues/219. Our log file directory structure is like this:
log_dir/
log1
log2.gz
log_archive_folder/
Currently, with log pattern "/tmp/logs/*" , mtail cannot ignore the log2.gz and subfolder log_archive_folder. Therefore I implemented the feature to ignore any subfolder and files whose filenames are matched by regex  pattern. Tests are added.
> add regex pattern to ignore file and ignore subfolder

- internal/mtail/mtail.go
- internal/vm/loader.go
- internal/vm/vm_integration_test.go
- internal/watcher/log_watcher.go
- internal/watcher/log_watcher_test.go
Make the internal metric names consistent, follow Prometheus/OpenMetrics
naming conventions.
> Use consistent naming for internal metrics

- .circleci/config.yml
The `container` phase of the workflow was missing tags so it was never
run, which causes the release to not be published.
> Add missing filter to container workflow

- README.md
- docs/Language.md
- docs/index.md
- examples/linecount.mtail
- internal/mtail/basic_tail_integration_test.go
- internal/mtail/glob_relative_after_start_integration_test.go
- internal/mtail/log_glob_integration_test.go
- internal/mtail/mtail.go
- internal/mtail/mtail_test.go
- internal/mtail/multiple_lines_integration_test.go
- internal/mtail/partial_line_integration_test.go
- internal/mtail/read_pipe_integration_test.go
- internal/mtail/truncate_integration_test.go
- internal/vm/codegen/codegen_test.go
- internal/vm/loader.go
- internal/vm/parser/lexer_test.go
- internal/vm/parser/parser_test.go
Make `line_count` into `lines_total` to be consistent with naming
convention.
> Make line count consistent

- docs/Programming-Guide.md
Fix the RFC3339 time parsing layout. The regexp correctly matched the time zone offset (07:00), but the time parsing layout incorrectly left out the colon (0700).
> doc: fix date format layout

- README.md
Noticed a small issue introduced with commit  https://github.com/google/mtail/commit/395e1a328c4db3699301129176194953eb9db693
> Fix fuzzit badge trailing link

- docs/faq.md
- internal/exporter/prometheus.go
Change the wording of the timestamp handling documentation. The
current wording is incorrect and is misleading and confusing users.
> Improve documentation of timestamp handling

- cmd/mtail/main.go
> Set exit code to 0 when outputting version info.

- internal/exporter/json_test.go
- internal/metrics/datum/buckets.go
When outputting JSON (with -one_shot for example), the +Inf bucket bound
could not be marshaled as a JSON number and caused mtail to crash.
This stringifies the buckets bounds and solves this issue.
Resolves: https://github.com/google/mtail/issues/273
> MarshalJSON bucket bounds as strings

- examples/apache_combined.mtail
> small comment fix in examples/apache_combined.mtail

- Makefile
I'd like to run this on arm64 machines, can we have released binaries for it as well?
See also: 49d933dff0ed9cebb6f6a1f98bf63ade823a9953
> Makefile: Add linux/arm and linux/arm64 release

- README.md
Google groups has changed their URL format, so to avoid a redirect let's use the new destination.
> Update the URL to the user mailing list.

- internal/testutil/timeout.go
- internal/testutil/timeout_test.go
Attempt to deflake the timeout test by breaking it into separate test methods
to identify the regular flaker.
Also increase the deadline for the flake.
Add a test for always returning an error.
> Refactor the timeout test.

- internal/vm/loader.go
- internal/vm/vm.go
It already knows what the name is, and CodeQL thinks this is an XSS.
> Don't need to pass the name of the prog to the prog dumper.

- .github/workflows/golangci-lint.yml
This is in the step, not the job, per discussion in
https://github.com/actions/toolkit/issues/399 which indicates that a
continue-on-error at the job level would cause the icon to still be a cross,
but at the step level is totally ignored.  Right now golangci-lint doesn't work
for mtail due to https://github.com/golangci/golangci-lint/issues/1559 so let's
leave it running but ignore it totally with the former setup.
> Mark golangci-lint continue on error.

- cmd/mtail/main.go
- internal/mtail/mtail.go
- internal/mtail/options.go
- internal/tailer/tail.go
- internal/tailer/tail_test.go
Move all filesystem polling out of mtail.Server and into the Tailer.  This centralises that work in the obvious place, and as a result the Tailer startup and shutdown code is simpler and less leaky back into the server.
Plumb a cancellable context through and use that for cleanup assistance, so we don't need to store internal config like the tick intervals.
> Improve tailer setup and teardown.

- internal/watcher/log_watcher_test.go
The order of events is unstable.
> Skip the log watcher test as it's flaky.

- .github/workflows/benchmark-done.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci-done.yml
- .github/workflows/ci.yml
I've misunderstood how the latter works, until reading
https://securitylab.github.com/research/github-actions-preventing-pwn-requests.
The parts that comment on PRs need to run in a workflow_run event after saving
artifacts.
> Use pull_request, not pull_request_target to trigger workflows.

- .github/workflows/ci.yml
Most of the cache will hit on every PR, so why not.
Via https://github.com/mvdan/github-actions-golang
> Cache the go build cache to speed up incrementals.

- Makefile
When looking to see if we can compare benchmark results, the base_ref filename was incorrect.
> Fix the name of the base benchmark file.

- .github/workflows/ci.yml
This test was a leftover from when the test publish action was running from pull_request_target, now it's preventing tests from running on in-repo branches.
> Remove condition from CI test job.

- Makefile
Now the benchmarks appear to work again quickly, run in multiple CPU counts so we can see how that varies performance.
> Run benchmarks on various CPU counts.

- internal/exporter/export.go
- internal/exporter/prometheus.go
- internal/exporter/varz.go
- internal/metrics/store.go
- internal/metrics/store_bench_test.go
- internal/mtail/examples_integration_test.go
- internal/mtail/golden/reader.go
The post in The Little Go Book of Semaphores
https://blog.ksub.org/bytes/2016/04/10/the-search-insert-delete-problem/ is a
fascinating read -- well, the whole thing is really -- and suggests a solution
to the general case here.  I think this is actually overkill -- we don't delete
anyuthing from the store except in initialisation (which is probably also
unnecessary) so we don't need the inserter lock as well -- the problem is
probably just that Add took the wrong lock during the search part.  However it
was fun to figure out how to apply this pattern and if we can't have fun, why
are we even here?
Benchmarks shows a massive reduction in time for the new Store/Add and
Store/Iterate families.
Issue #341
> Switch the store RWMutex to a pair of categorical mutices.

- cmd/mtail/main.go
- internal/mtail/examples_integration_test.go
- internal/mtail/mtail.go
- internal/mtail/options.go
We don't need to do it in mtail because it happens after shutdown.  The option
can be removed because it only gets set in tests.
> Move the metrics store dump to the main function.

- internal/vm/loader.go
Current build is unable to reload programs on HUP, logging that
```
I0127 23:04:43.886579   13546 loader.go:434] no program reload on SIGHUP without programPath
```
apparently there is a trivial typo in path check.
> fix SIGHUP handler: check for non-empty path to programs

- internal/tailer/logstream/pipestream.go
This is a normal condition so we should not be logging this at info level, it's
debugging information.  Otherwise we'll fill the mtail logs!
Fixes #462
> Downgrade the timed out message from pipestream as it's expected.

- internal/exporter/export_test.go
- internal/exporter/graphite.go
- internal/exporter/graphite_test.go
- internal/mtail/httpstatus.go
- internal/mtail/mtail.go
Up until now when exporting histograms for Graphite only the sum of the values was being exported as one metric. From now on the counts of values in distinct buckets along with the total count is exported too, as separate metrics, so histograms are now usable in Graphite too.
Perhaps similar code should be added to collectd, statsd and varz metricTo* converters too...
Additionally Graphite metrics are now exported via HTTP which can sometimes ease debugging.
> Export histogram buckets and total count for Graphite

- internal/waker/testwaker.go
- internal/waker/testwaker_test.go
There was a race where we'd skip ahead in the `Wake()` and accidentally wait on
the same wake channel a second time, which would get the wrong result when that
occurs because it would have been `awaken()`d by then.  Forcing the first
iteration to block on `Wake()` ensures the second one gets a new channel.
> Correct TestTestWakerTwoWakeups by waiting for the actual wakeup.

- internal/tailer/logstream/pipestream_test.go
The test was correct, but due to golang/go#44176 we must make sure the writer
end is open first.
Issue #486
> Reorder the test to avoid a deadlock.

- Makefile
When the branch name contains slashes, the file fails to be created.  Previous
attempt to rewrite the file with a substitution reference was not working
because substitution references are equivalent to `patsubst`.  This time use
simple expansion and a `subst` call.
> Fix the name substitution of the benchmark results filename.

- .github/workflows/automerge.yml
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
says dependabot now triggers in read only mode.
> Use pull_request_target on the automerge action.

- docs/Language.md
- docs/Programming-Guide.md
- internal/vm/checker/checker_test.go
- internal/vm/code/opcodes.go
- internal/vm/codegen/codegen.go
- internal/vm/codegen/codegen_test.go
- internal/vm/parser/lexer.go
- internal/vm/parser/lexer_test.go
- internal/vm/parser/parser_test.go
- internal/vm/types/types.go
- internal/vm/vm.go
- internal/vm/vm_integration_test.go
- internal/vm/vm_test.go
With the new `subst` function we can remove and convert bits from a capture group that we don't want, like stray commas and underscores.
Documented in the Programming Guide on the two patterns that showed up in the bug reports.
Fixes #254, fixes #326, fixes #424
> Implement string substitution function

- internal/mtail/read_pipe_integration_test.go
- internal/tailer/logstream/cancel.go
- internal/tailer/logstream/pipestream.go
- internal/tailer/logstream/pipestream_test.go
https://github.com/golang/go/issues/20280#issuecomment-655588450 has an
excellent example on how to interrupt a read on context cancellation, which
means we don't need to set a read deadline on every read attempt.  Then, the
error handling is simplified, and as a side effect we aren't having spurious
wakeups on idle fifos.
This also means we no longer have a race on first read when the write end of a
fifo isn't ready.
Issue: #486
> Simplify pipestream by correctly interrupting a read on context cancellation.

- internal/runtime/compiler/checker/checker.go
- internal/runtime/compiler/checker/checker_test.go
- internal/runtime/compiler/codegen/codegen_test.go
- internal/runtime/compiler/parser/parser.go
- internal/runtime/compiler/parser/parser.y
- internal/runtime/compiler/parser/y.output
The parser was incorrectly setting a position based on the token position at
the end of a production.  We must select the entire production so we must
mark_pos first and then merge the mark and current pos when setting positions.
> Fix positions for builtins and other long expressions.

- internal/tailer/logstream/decode.go
> Skip over \r when decoding a line of text from a log.

- internal/tailer/logstream/dgramstream.go
- internal/tailer/logstream/dgramstream_test.go
- internal/tailer/logstream/logstream.go
- internal/tailer/logstream/socketstream.go
- internal/tailer/logstream/socketstream_test.go
- internal/tailer/tail.go
- internal/testutil/port.go
Now we can listen on a host/port and receive TCP or UDP logs, though I don't like it because it opens mtail up for more feature requests around security, but the new Interoperability document does suggest alternatives.
> Support IP stream and datagram sockets.

- .github/workflows/ci.yml
- Makefile
- TODO
- cmd/mdot/main.go
- cmd/mgen/main.go
- internal/runtime/runtime.go
- internal/testutil/fs.go
Hi maintainers! 
I work at [Bison Trails](https://bisontrails.co/). We're doing an internal hackathon this week.
Our team loves `mtail`, but it got flagged during a recent security review. Our team voted to use our hackathon time to patch vulnerabilities in our favorite OSS tools and specifically to try to get `mtail` approved for usage within our organization. 
- adds `gosec` security scans to github actions
- addresses the HIGH + MEDIUM severity issues from `gosec` scan
These changes should improve `mtail`'s security posture. We identified these vulnerabilities using [Salus](https://github.com/coinbase/salus) and the [OSSF scorecard](https://github.com/ossf/scorecard). The specific issues I am hoping to address here are:
```
[/mtail/cmd/mgen/main.go:98] - G404 (CWE-338): Use of weak …
```
> Add gosec scans to mtail CI

- examples/apache_metrics.mtail
We need to use floating point division, instead of integer division,
otherwise the values end up as wrong and unexpected numbers in the
histogram's buckets.
> examples/apache_metrics.mtail: fix http_request_duration_seconds division

- cmd/mtail/main.go
- internal/exporter/prometheus.go
- internal/exporter/prometheus_test.go
This provides an easier to develop mtail programs because the Prometheus
exposition format is more concise.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Add -one_shot_format to support Prometheus one shot output

- internal/runtime/compiler/checker/checker.go
- internal/runtime/compiler/checker/checker_test.go
- internal/runtime/compiler/types/types.go
- internal/runtime/compiler/types/types_test.go
- internal/testutil/diff.go
Refactor type checking so that we can assign a type based on the returned value of `types.Unify()`.
> Unify returns Type

- internal/runtime/compiler/checker/checker.go
- internal/runtime/compiler/checker/checker_test.go
- internal/runtime/compiler/types/types.go
- internal/runtime/compiler/types/types_test.go
- internal/runtime/runtime_integration_test.go
Clean up the error messages used in type mismatch reporting.
Standardise the form used when constructing types for unification.
> Type reporting cleanup

- .github/workflows/automerge.yml
We now have the correct permissions to reduce the surface of the token.
> Fix permissions and triggers for the dependabot auto merge.

- .github/workflows/automerge.yml
Principle of least privilege says let's break these up and give each step only
the permissions it needs to get the job done.
> Refactor the dependabot workflow into multiple jobs.

- internal/tailer/tail_test.go
- internal/testutil/file.go
This avoids dual awaken races because we're making sure the data is where we
thought it was.
Thanks to @Loyilee for discovering this issue.
Issue: #603
> If WriteString writes to an actual file, then Sync to disk.

- cmd/mtail/main.go
- docs/Deploying.md
- internal/mtail/testing.go
- internal/tailer/tail.go
- internal/tailer/tail_test.go
Hi,  i'm using mtail to monitor the docker logs of the machine, and every machine has 500+ matched log files .  Below is the configuration:
```
mtail --progs /etc/mtail --logs "/home/docker/logs/*/*/*/*/*/platform-*.log" --expired_metrics_gc_interval 10m
```
I notice that mtail always keeps more than 60% cpu usage, **even no logs produced**.   After profiling the process, i found that the primary reason is **tailer#PollLogPatterns**  calls frequently (run per 250ms by default).  We can't separately control the interval of poll-log-pattern or poll-log-stream.  I tried to split the option and deployed the fixed mtail on production for a few weeks, and it works well.  Could you help me to review the feature?
> Split pollInterval option to reduce filepath.Glob overhead

- internal/mtail/testing.go
- internal/tailer/tail.go
- internal/tailer/tail_test.go
- internal/testutil/file.go
- internal/waker/testwaker.go
Test synchronisation relies on the logstreams being the only wakee waiting on
the testwaker.  If we use it in a second stream, we either have to bump the
awaken counter or remove it.
The PollLogstream method was incorrectly named; renaming for more clarity means
we see that we don't need to call it on the same waker but instead clean up
streams when we poll for new patterns, less frequently but frequent enough.
This undoes some of the changes from #603 as mentioned in that comment thread.
> Don't run a second goroutine on the logstreamWaker.

- Makefile
- internal/mtail/examples_integration_test.go
This PR increases the timeouts for tests using TestTimeout, as well as the `go
test` timeout, to avoid frequent failures in slow machines.
Closes: #611
> Increase test timeouts

- internal/mtail/examples_integration_test.go
- internal/mtail/log_deletion_integration_test.go
* 8ae3a26  - Avoid test hang when net.Conn.Write times out
As described in #614, some times writing a zero-length message fails with a 
time out error, causing the goroutine to fail without marking the stream as 
finished, and so the test server never finishes.
This commit adds a work-around by retrying the `Write` call until it succeeds
or returns a non-timeout error. It also adds a `Sleep` call between tries as 
otherwise this becomes a spin loop, filling the log with timeout errors.
* c4be4d97 - Fix race in TestLogDeletion
As described in #614, I discovered a race condition in this test which
results in the test blocking forever. This commit fixes the issue by calling
`PollWatched` before deleting the log file.
Closes: #614
> Fix tests hanging

- docs/Language.md
- internal/metrics/metric.go
- internal/metrics/metric_test.go
- internal/metrics/store.go
- internal/metrics/store_test.go
- internal/runtime/compiler/ast/ast.go
- internal/runtime/compiler/codegen/codegen.go
- internal/runtime/compiler/parser/lexer.go
- internal/runtime/compiler/parser/parser.go
- internal/runtime/compiler/parser/parser.y
- internal/runtime/compiler/parser/parser_test.go
- internal/runtime/compiler/parser/unparser.go
- internal/runtime/compiler/parser/y.output
The new keyword `limit` on a metric declaration specifies a storage size limit on simultaneous label values; if the metric exceeds that size then the next GC run will remove the oldest by timestamp until it is back under the limit.
Fixes #617
> Add metric size limits to the language and metric store.

- internal/exporter/export.go
- internal/exporter/export_test.go
When parsing statsd/graphite metrics with the positional [telegraf templates](https://docs.influxdata.com/telegraf/v1.22/data_formats/template-patterns/), the order of labels is critical.
Thus let's ensure that the order of labels in the export is stable by sorting them.
Signed-off-by: Andreas Jaggi <andreas.jaggi@waterwave.ch>
> Stabilize order of labels in statsd/graphite/collectd export

- go.mod
https://github.com/google/mtail/commit/e494568bb97919b22caeb7949a8158dc0c7238b2#r77513974
indicates that math.MaxInt is not available earlier.
> Raise minimum Go version to 1.17.

- internal/tailer/logstream/decode.go
- internal/tailer/logstream/filestream.go
- internal/tailer/logstream/filestream_test.go
We need catch the utf8.RuneError when decode the file stream.
Detail see issue: #637
> Fix Unicode replacement character appear in parse result

- .github/workflows/ci.yml
Extract a SHA from post-merge on main.
Set the shell explicitly to `bash` which means we also correctly `if` and thus are likely to succeed as `pwsh` is a totally different language!  Fun times in Github Actions.
> ci: Select the correct sha for the test results when running from a post-merge action.

- .github/workflows/ci.yml
Use the setup-go cache feature.
> ci: Use the version of go specified in go.mod

- cmd/mtail/main.go
- internal/mtail/httpstatus.go
- internal/mtail/mtail.go
- internal/mtail/options.go
- internal/runtime/httpstatus.go
- internal/tailer/httpstatus.go
fixes https://github.com/google/mtail/issues/305
Note: this is just https://github.com/google/mtail/pull/308 with the feedback incorporated (as the original went stale)
> Add http_debugging_endpoint and http_info_endpoint flag to allow disabeling http debug endpoints

- internal/tailer/logstream/decode.go
- internal/tailer/logstream/filestream_test.go
Fix for a memory leak which is hitting us on v3.0.0-rc50.
When a corrupt unicode character is received, mtail stops processing logs and instead buffers them in memory. It happens because a recent change ( c12a012 ) has made it so parsing of bytes in the log buffer to runes is being retried when parsing results in a RuneError. I guess that change was made under the assumption that rune errors are always recoverable (you just need to increase the buffer), but that is not the case. In production we've seen this memory leak happen multiple times since we deployed the new version of mtail.
With this commit RuneErrors on parsing unicode characters are ignored when there are enough characters after it in the buffer.
This keeps the functionality intact that bytes that gave a RuneError are being …
> Fix memory leak on corrupt unicode character

- .github/workflows/release.yml
See if this fixes the goreleaser snapshot mode on pull_request.
> ci: Downgrade goreleaser action.

- .github/workflows/benchmark-done.yml
- .github/workflows/ci-done.yml
Resolve  #726 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=comment::$COMMENT"
```
**TO-BE**
```yml
echo "comment=$COMMENT" >> $GITHUB_OUTPUT
```
> Replace deprecated command with environment file

- .goreleaser.yml
This has been deprecated and removed upstream.
> ci: Remove the archives.replacements field from the goreleaser config.

- docs/Language.md
> doc: Expand on the first argument to `subst`.

- examples/postfix.mtail
Otherwise the "application" regex group won't match a string such as "postfix/postfix-script"
> examples/postfix.mtail - move dash to end of character class

- docs/Deploying.md
Link to a Go bug about strange dual-stack behaviour.
Fixes: #775
> doc: Document the `--address` commandline flag.

- .github/workflows/ci-done.yml
- .github/workflows/ci.yml
This should avoid a 409 Conflicts in `upload-artifact@v4` which doesn't like
the conflicting artifact name anymore.
> Run the ci-done on each `runs-on`, and separate test result upload by platform.

- .github/workflows/release.yml
Move the `goreleaser` permissions directly onto the job rather than the whole
workflow, as #771 is going to add a second job with different requirements.
> ci: Bind permissions as tight as possible.

- internal/metrics/datum/buckets.go
- internal/runtime/compiler/codegen/codegen.go
- internal/runtime/runtime_integration_test.go
Currently, mtail checks both lower and upper bound when searching for a histogram bucket. This is not only unnecessary (because buckets are constructed so that they are sorted and continuous), it leads to bugs like https://github.com/google/mtail/issues/226 (fixed in the past), https://github.com/google/mtail/issues/675 (still open) and the fact that negative values will not be counted in any bucket unless you explicitly add negative bucket that is lower than any value that will be observed (which is not a problem for timings, but histograms could be used for other things).
Behavior of other prometheus clients is to look for first bucket where observed value less or equal to its upper bound. This MR makes mtail to also behave this way, which ensures any observation will always be counted …
> Histogram zero fix

- .github/workflows/release.yml
Adds a docker image build and push to release workflow/job.
The resulting docker image is pushed to the Github Container Registry (not on pull requests).
The image name is based on the Github Repository path and should result in ghcr.io/google/mtail.
closes https://github.com/google/mtail/issues/674
> Publish docker image to GitHub Container Registry

- go.mod
- go.sum
- internal/exporter/prometheus.go
`prometheus/common` made a breaking change in `expfmt` with
https://github.com/prometheus/common/pull/576 so we need to change the prometheus encoder constructor
and the dependency version of both `common` and `client_golang` in the same PR.
> Bump prometheus library versions.

- mtail.service
This imports a unit file allowing users to run mtail as a system service on systemd based systems.
Submitted on behalf of a third-party: openSUSE contributors
Contributed from https://build.opensuse.org/package/view_file/server:monitoring/mtail/mtail.service as per the discussion in https://github.com/google/mtail/issues/314.
> Add systemd service unit file

- internal/mtail/mtail.go
Prometheus upstream has made another breaking change and rearranged the client
code (without a deprecation notice :D
This will fix the merge of prometheus/common@0.50.0 in #818.
> chore: Change the callsite of the version collector.

- internal/mtail/mtail.go
This PR fixes the formatting of import statements in one file.
The PR arose when I ran [`gci`](https://github.com/daixiang0/gci) linter and found that this tool broke on imports with TABS at the end:
```
❯ gci diff internal/mtail/mtail.go
Error: 26:42: expected ';', found "go.opencensus.io/zpages" (and 7 more errors)
```
But when I remove this TAB the`gci` working fine:
```
❯ gci diff internal/mtail/mtail.go
--- internal/mtail/mtail.go
+++ internal/mtail/mtail.go
@@ -21,8 +21,8 @@
"github.com/google/mtail/internal/tailer"
"github.com/prometheus/client_golang/prometheus"
"github.com/prometheus/client_golang/prometheus/collectors"
-       "github.com/prometheus/client_golang/prometheus/promhttp"
vc "github.com/prometheus/client_golang/prometheus/collectors/version"
+ …
```
> chore: Remove excessive TAB in one import statement

- .github/workflows/golangci-lint.yml
- .golangci.yml
- cmd/mdot/main.go
- internal/metrics/metric_test.go
- internal/metrics/store_bench_test.go
- internal/mtail/mtail.go
This PR fixes the [failing](https://github.com/google/mtail/actions/runs/8442491054) `golangci-lint` GitHub workflow. It became failing after merging #813 ([action](https://github.com/google/mtail/actions/runs/8104054505/job/22149885469)).
The golangci-lint workflow is failing because golangci-lint v1.52 was [built](https://github.com/golangci/golangci-lint/blob/v1.52.2/go.mod#L3) with Go 1.19, so it's unfamiliar about Go 1.21 features that this repo is using.
Changes:
- Update the golangci-lint version to `v1.57` in `.github/workflows/golangci-lint.yml`. This version is the latest and is compatible with Go 1.21.
- Fix `.golangci.yml` config and disable all new linters after v1.52. Likely, we will fix issues from them later.
- Fix simple issues from the `revive` linter about an unused …
> chore: Bump golangci-lint version to v1.57

- internal/tailer/tail.go
- internal/tailer/tail_test.go
'??' glob pattern for --logs argument used to work (in v3.0.0-rc36) but stopped working in recent versions.
I have the following log files:
```
/var/log/my_prog/my_prog.log.20220419_14
/var/log/my_prog/my_prog.log.20220419_15
```
I am starting the latest build of mtail with the following arguments:
`/tmp/mtail.rc48 -port 12345 -progs /etc/mtail/my-progs/ -logtostderr -disable_fsnotify -logs '/var/log/my_prog/my_prog.log.*_??'`
Mtail does not tail the files:
```
runtime.go:188] Loaded program sockets.mtail
runtime.go:84] unmarking sockets.mtail
mtail.go:126] Listening on [::]:12345
```
If I start it with:
`/tmp/mtail.rc48 -port 12345 -progs /etc/mtail/my-progs/ -logtostderr -disable_fsnotify -logs '/var/log/my_prog/my_prog.log.*_[0-9][0-9]'`
It tails the files:
```
runtime.go:188] Loaded …
```
> '??' glob pattern not working in recent versions for --logs argument

- .github/workflows/release.yml
The archives are just source; we want all the tarballz and zips created by the
release.
Issue: #836
> ci: Download all tarballs, not archives.

- .github/workflows/release.yml
Avoid "no files match this pattern" error by just getting them all. We need all anyway to verify.
> ci: Download all assets in one go

- .github/workflows/release.yml
- .goreleaser.yml
The previous attempt couldn't find the images in the attestation.
Instead copy the goreleaser example
https://github.com/goreleaser/goreleaser-example-slsa-provenance/blob/master/.github/workflows/goreleaser.yml
and separate these two.
Issue: #836
> ci: Split up image and binary verification.

- .github/workflows/tag-new-release.yml
- .releaserc.js
Set up semantic-release to ignore `ci` type and mark some other common ones as
patch.
> ci: Workflow for tagging a new release.

- cmd/mtail/main.go
- internal/exporter/export.go
- internal/exporter/export_test.go
- internal/exporter/graphite_test.go
- internal/exporter/json_test.go
- internal/exporter/prometheus_test.go
- internal/exporter/varz_test.go
- internal/mtail/mtail.go
The `Exporter` and `HTTPServer` are not connected by channels to the `Runtime`,
only indirectly through mutating effects on the Store. As such we can't rely on
the `Exporter` to shut down automatically when the `Runtime` shuts down.
Here instead we remove the `WaitGroup` and allow an `Exporter` to be shut down
explicitly after the `WaitGroup` is `Done`.
Issue: #331
> Explicitly stop the `Exporter` when main routines are done.

- .github/workflows/benchmark.yml
Benchmark name extraction is broken and makes incorrect reports.
> ci: Disable benchmark workflow

- internal/tailer/logstream/dgramstream.go
- internal/tailer/logstream/logstream.go
- internal/tailer/logstream/pipestream.go
The pipe buffer size had been chosen to match the system default buffer size on Linux, but increasing all buffer sizes makes throughput faster by reducing the number of syscalls for large reads.
Tested logically by the bandwidth-delay product.
Tested experimentally per the linked bug.
Fixes: #685
> fix: Raise the read buffer sizes to 128KiB.

- .github/workflows/release.yml
GITHUB_TOKEN can't cause new workflows to run.  That's the core problem with `on: create:` in this case; the tag-new-release workflow doesn't issue the create event, because the github-actions credential isn't allowed to do so.
> ci: Run this workflow on tag push again.

- internal/tailer/logstream/dgramstream.go
- internal/tailer/logstream/dgramstream_unix_test.go
- internal/tailer/logstream/filestream.go
- internal/tailer/logstream/filestream_test.go
- internal/tailer/logstream/filestream_unix_test.go
- internal/tailer/logstream/logstream.go
- internal/tailer/logstream/pipestream.go
- internal/tailer/logstream/socketstream.go
- internal/tailer/logstream/socketstream_unix_test.go
- internal/tailer/tail.go
This improves the interface for stream shutdown, though we can't remove `Stop` completely yet.
Also fixes `oneShot` handling in various streams.
Issue: #199
> fix: Use context cancellation instead of `Stop` to stop streams.

- Dockerfile.goreleaser
Container runtimes can't find their entrypoint because the search path?
Issue: #880
> fix: Give a full path in Dockerfile ENTRYPOINT

- README.md
GitHub Q&A seems to be easier and more visible than the mailing list.
> doc: Update the instructions for asking for help.

- internal/runtime/compiler/ast/ast.go
`gosec` thinks that `l[0].Pos()` is an index out of range error.
> chore: reformat ast mergepositionlist because gosec is buggy

- internal/tailer/logstream/dgramstream.go
- internal/tailer/logstream/dgramstream_unix_test.go
- internal/tailer/logstream/filestream.go
- internal/tailer/logstream/filestream_test.go
- internal/tailer/logstream/filestream_unix_test.go
- internal/tailer/logstream/logstream.go
- internal/tailer/logstream/logstream_test.go
- internal/tailer/logstream/logstream_unix_test.go
- internal/tailer/logstream/pipestream.go
- internal/tailer/logstream/pipestream_unix_test.go
- internal/tailer/logstream/socketstream.go
- internal/tailer/logstream/socketstream_unix_test.go
- internal/tailer/tail.go
- internal/testutil/lines.go
This makes it easier to observe logstream state externally because we can read
the lines channel until it closes.
The tests are changed slightly to asynchronously drain the output channel at
the start of the stream.
Fix some naming issues and log formatting.
> fix: LogStreams create and close their own lines channels.

- cmd/mtail/main.go
- internal/mtail/log_deletion_integration_unix_test.go
- internal/mtail/log_glob_integration_test.go
- internal/mtail/log_rotation_integration_test.go
- internal/mtail/log_rotation_integration_unix_test.go
- internal/mtail/options.go
- internal/mtail/testing.go
- internal/tailer/logstream/dgramstream.go
- internal/tailer/logstream/dgramstream_unix_test.go
- internal/tailer/logstream/filestream.go
- internal/tailer/logstream/filestream_test.go
- internal/tailer/logstream/filestream_unix_test.go
- internal/tailer/logstream/logstream.go
- internal/tailer/logstream/pipestream.go
- internal/tailer/logstream/pipestream_unix_test.go
- internal/tailer/logstream/socketstream.go
- internal/tailer/logstream/socketstream_unix_test.go
- internal/tailer/tail.go
- internal/tailer/tail_test.go
Removes most of the `LogStream` interface functions, moving some functionality into the `LogStream` and using only closure of the lines channel to signal stream shutdown.  All external notices are now handled by `Context` cancellation.
The `stale_log_gc_interval` flag is now deprecated as these are cleaned up at stream shutdown.
Issue: #199
> Fix: Use channel semantics to manage `LogStream` lifecycle in `Tailer`.

- internal/tailer/logstream/dgramstream.go
- internal/tailer/logstream/dgramstream_unix_test.go
- internal/tailer/logstream/filestream.go
- internal/tailer/logstream/pipestream.go
- internal/tailer/logstream/pipestream_unix_test.go
- internal/tailer/logstream/socketstream.go
- internal/tailer/logstream/socketstream_unix_test.go
Copying the filestream, now pipe, dgram, and socket streams return to read
again immediately after a successful read, so that we don't wait.
This is now obviously the problem in #685 and using the bandwidth-delay-product
we can see that a 250ms pause between reads of 4096B and 128KiB matches the
results seen.
Before:
```
jaq% time ./mtail -logs - -progs examples/rsyncd.mtail < internal/mtail/testdata/rsyncd.log
0.01s user 0.01s system 7% cpu 0.264 total
```
After:
```
jaq% time ./mtail -logs - -progs examples/rsyncd.mtail < internal/mtail/testdata/rsyncd.log
0.01s user 0.03s system 102% cpu 0.041 total
```
Thanks to @rideliner for the hint.
Issue: #685
> fix: Return to read immediately after a successful read.

- internal/mtail/mtail.go
This change updates the HTTP server's write timeout to 5 seconds to ensure the exporters have enough time to write their output.
> feat: update HTTP server write timeout to 5 seconds

- internal/runtime/compiler/checker/checker.go
- internal/runtime/compiler/checker/checker_test.go
This change updates the ``checkRegex`` helper to not track symbols for a regexp when it is used by the builtin ``subst``. In this case the VM will not store these matches, and therefore these symbols will not be available to the program. The compiler will, however, compile these regexp and add them to the regexp table for use by the VM, and multiple calls to ``subst`` are already handled by the VM.
fixes: https://github.com/google/mtail/issues/693, fixes: https://github.com/google/mtail/issues/810
> fix: fix symbol checking and creation for ``subst`` with a regexp
